name: Setup

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Cargo cache setup
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/
          ~/.rustup/toolchains/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Just setup
      uses: extractions/setup-just@v2

    - name: Leptosfmt setup
      shell: bash
      run: cargo install leptosfmt@0.1.30
