edition = "2021"
condense_wildcard_suffixes = true
error_on_line_overflow = false
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
max_width = 80
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
